### ISSUE TITLE
About source code

### ISSUE THREAD

**Issue by neofeo** [Tahlreth/tahlreth.github.io#1]
Hi!! Is there any plan to release the source down the road..
And if you don't, is there any change to get releases as libretro cores or CLI standalone arm64 linux releases?

Thanks for your effort.

**Comment by Sans727277** [comment]
Can't wait for release

**Comment by Tahlreth** [comment]
You will be able to recompile/link the LGPL portions of the library used in the android app, in compliance with the license.
